FROM maven:3-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -Dmaven.test.skip=true

FROM eclipse-temurin:21-alpine
WORKDIR /app
COPY --from=build /app/target/server-1.0-SNAPSHOT-jar-with-dependencies.jar .
CMD ["java", "-jar", "server-1.0-SNAPSHOT-jar-with-dependencies.jar"]
